export const newProduct = {
  title: {
    "Product": "Add New Product",
  },
  getServerDetails: {
    url: '/rest/admin/new_product',
    isFormData: true
  },
  tabs: {
    "Product": {
      "Product": [
        {
          type: "input",
          name: "product_name",
          headerName: "Product Name",
          width: '300px',
          value: "",
          required: true,
          height: 9
        },
        {
          type: "input",
          name: "product_name_bahasa",
          headerName: "Nama Produk",
          // value: props["Product Name"] || "",
          width: '300px',
          required: true,
          height: '9px'
        },
        {
          type: "input",
          name: "production_code",
          headerName: "Production Code",
          // value: props["Company Name"] || "",
          placeholder: "XX-XXX-XX-XX",
          width: '300px',
          required: true,
          height: '9px',
        },
        {
          type: "input",
          name: "production_code",
          headerName: "Kode Produk",
          placeholder: "XX-XXX-XX-XX",
          // value: props["Product Code"] || "",
          width: '300px',
          required: true,
          height: '9px'
        },
        {
          type: "input",
          name: "product_general_name",
          headerName: "Product",
          // value: props["Farm Name"] || "",
          width: '300px',
          height: "9px",
          required: true
        },
        {
          type: "input",
          name: "product_general_name_bahasa",
          headerName: "Produk",
          // value: props["Farm Name"] || "",
          width: '300px',
          height: "9px",
          required: true
        },
        {
          type: "attach-image",
          name: "product_picture",
          headerName: "Add Image",
          // value: props["Farm Name"] || "",
          width: '272.05px',
          height: 240,
          required: true
        },
        {
          type: "dropdown",
          name: "category_id",
          headerName: "Category",
          // value: props["Farm Contact"] || "",
          optionUrl: '/rest/metadata',
          optionMainVariable: "cropCategories",
          optionVariable: "category_name",
          width: '300px',
          required: true,
          height: '41px',
          dependent: "category_id_bahasa",
          dependentVariable: "category_name_bahasa"
        },
        {
          type: "dropdown",
          name: "category_id_bahasa",
          headerName: "Kategori",
          // value: props["Farm Contact"] || "",
          optionUrl: '/rest/metadata',
          optionMainVariable: "cropCategories",
          optionVariable: "category_name_bahasa",
          width: '300px',
          required: true,
          height: '41px',
          dependent: "category_id",
          dependentVariable: "category_name",
        },
        {
          type: "input",
          name: "variant_name",
          headerName: "Variant",
          placeholder: 'Variant Name...',
          // options: [
          //   'Green',
          //   'Red',
          //   'Purple',
          //   'Sweet',
          //   'Red Cayenne',
          //   'Cherry',
          //   'Rawit Green',
          //   'Rawit Red',
          //   'Acar',
          //   'Roma',
          //   'Beef',
          //   'Italian',
          //   'Thai'
          // ],
          // value: props["Contact Number"] || "",
          width: '300px',
          required: true,
          height: '9px'
        },
        {
          type: "input",
          name: "variant_name_bahasa",
          headerName: "Variant",
          placeholder: 'Variant Name...',
          // options: [
          //   'Green',
          //   'Red',
          //   'Purple',
          //   'Sweet',
          //   'Red Cayenne',
          //   'Cherry',
          //   'Rawit Green',
          //   'Rawit Red',
          //   'Acar',
          //   'Roma',
          //   'Beef',
          //   'Italian',
          //   'Thai'
          // ],
          // value: props["Contact Number"] || "",
          width: '300px',
          required: true,
          height: '9px'
        },
        {
          type: "dropdown",
          placeholder: 'Select Maturity',
          headerName: "Maturity",
          width: '300px',
          required: true,
          height: '41px',
          type: "dropdown",
          name: "maturity_id",
          optionUrl: '/rest/metadata',
          optionMainVariable: "cropMaturities",
          optionVariable: "maturity_type",
          dependent: "maturity_id_bahasa",
          dependentVariable: "maturity_type_bahasa",
        },
        {
          type: "dropdown",
          placeholder: '',
          headerName: "Kematangan",
          width: '300px',
          required: true,
          height: '41px',
          type: "dropdown",
          name: "maturity_id_bahasa",
          optionUrl: '/rest/metadata',
          optionMainVariable: "cropMaturities",
          optionVariable: "maturity_type_bahasa",
          dependent: "maturity_id",
          dependentVariable: "maturity_type",
        },
      ]
    },
  }
}